### ISSUE TITLE
Feature wish: basic library functionality for large files to ease navigation

### ISSUE THREAD

**Issue by topchyan** [be1/redrose#11]
Sometimes a single file contains literally hundreds of tunes. It would be great to have a way to find songs by name, composer, rhythm by having some kind of a summary list. of tunes in a given file. Right now X: box is the way to navigate, however enumeration may not be always correct -- all the tunes may have X:1 or X:999 which would make navigating through X box not very straightforward. Navigating and filtering through a summary list should be helpful.

**Comment by be1** [comment]
Interesting feature. I will think about it.
Meanwhile, as a workaround, you can use Ctrl-F in the text to search tune's title or composer (or right-click->find forward).

**Comment by be1** [comment]
I just pushed a very very basic implementation for navigation: now clicking on the X: spinbox's arrows will scroll the text window until that X tune, and display the associated score.

**Comment by topchyan** [comment]
Tried that and works good! Thanks!
