### ISSUE TITLE
Doesn't close 

### ISSUE THREAD

**Issue by topchyan** [be1/redrose#12]
I'm using it on Debian based Linux distro (MX-Linux). For some reason, I noticed that the program freezes and thus doesn't quit cleanly, so I encounter this.

![image](https://github.com/be1/redrose/assets/16518288/9b634fc2-6d07-4583-a152-c0a76a6190ba)

**Comment by be1** [comment]
Which action causes the freeze ?

**Comment by topchyan** [comment]
I can't pinpoint exactly, but I noticed that it can be triggered during the playback. Sometimes the tool displays a message on the status bar like "Playing 1 s" or "Synthesis finished" or "Score generated" and when you press Play button again it may no longer make a sound, then clicking additionally on various control simply freezes everything.

**Comment by be1** [comment]
This happened to me yesterday, once. I cannot reproduce though...

**Comment by be1** [comment]
I fixed a long standing bug in playback, with version 0.5.20 (July, 17; commit 896bfafdbba3bfec44d744da1c4d272e239cbb37) . Maybe the bug could also hang the application on pressing 'Stop' button. For now, I cannot reproduce this bug. @topchyan does it still appear for you as of version 0.5.23 ?

**Comment by topchyan** [comment]
I just build fresh it -- version number shows 0.5.19, so not sure if that's the same you're referring to. I was able to work with the tool and close without issues.

**Comment by be1** [comment]
@topchyan which `git branch` are your local repository on ?  0.5.19 is old. Did you `git pull` before to rebuild it ?
Note that since 0.5.20, the buld system has changed to CMake. So if you have an older build, please run:
```
make distclean
mkdir build
cd build
cmake ..
make
```
