### ISSUE TITLE
fluidsynth warnings and errors

### ISSUE THREAD

**Issue by topchyan** [be1/redrose#13]
Trying to work with this score, the program functions for a while, but then becomes unresponsive: the score no longer generates and fluidsynth errors seen in the console. Also noticing that individual notes on the score do not play even when the option is checked in the settings (I remember that before updating the program recently this feature worked and was very helpful).

![image](https://github.com/be1/redrose/assets/16518288/15d9e9ca-8691-41dd-acf7-25ff5e65d335)

```
X:6881
T: Hasapikos Horos
C: A. Sakellariou, A. Eptamenitis
B: From a 1936 publication by Apollo Music Co., New York.
M: 2/4
K: Gm
L: 1/8
%%MIDI drumbars 2
%%MIDI drum dd2ddddd 43 47 47 43 47 43 47
%%MIDI drumon
%%MIDI gchordbars 
%%MIDI gchord fcIc 
|: "D"a4         | ^f3 d       | "Cm"(3^fga (3gfe       | "D"(3g^fe d2 | \
   ^f2 g2        | a2 (3bag    | "Cm"^f>e (3gfe         | "D"(d2 d)z  :|
|: "D"d2 (3bag   | ^f>e (3fga  | "Cm"(3g^fe (3g^fe      | "D"d2 a2     | \ 
   "D"d2 (3bag   | ^f>e (3fga  | "Cm"(3g^fe (3g^fe      | "D"(d2 d)z  :|
|: "Cm"(3c=Bc d2 | (3ede ^f2   | (3^fga (3gfe           | "D"(3dcd a2  | \
   "Cm"(3c=Bc d2 | (3ede ^f2   | (3^fga (3gfe           | "D"(d2 d)z  :|
|: "D7"d>=B c>=B | d>=B c>=B   | dc A=B                 | "G"c2 =B2    | \ 
   G>=B c>=B     | G>=B c>=B   | G>=B c>=B              | "Am"(A2 A)z :|
|: "D"(3^fga aa  | aa (3^fed   | (3^fga aa              | aa d'2       | \ 
   "D"(3^fga aa  | aa (3^fed   | "Cm"d/e/^f/g/ a/g/f/e/ | "D"da dz    :|
%%sep
```

**Comment by be1** [comment]
X index is wrong on the UI. Please click on the area of the ABC score to update X index.
I will look how to fix it.

**Comment by be1** [comment]
Another error is that L: field must be written before K: field. The ABC specification says K: field is the last header field before V: or ABC stuff.

From https://abcnotation.com/wiki/abc:standard:v2.2#kkey
> Note that the first occurrence of the K: field, which must appear in every tune, finishes the [tune header](https://abcnotation.com/wiki/abc:standard:v2.2#tune_header_definition). All following lines are considered to be part of the [tune body](https://abcnotation.com/wiki/abc:standard:v2.2#tune_body_definition).

**Comment by be1** [comment]
This is now fixed in latest commit. Thanks for your bugreport.

**Comment by topchyan** [comment]
Works great! Thanks!
