### ISSUE TITLE
build warnings (harmless?)

### ISSUE THREAD

**Issue by topchyan** [be1/redrose#15]
I'm getting these warnings while trying to build 

parser.c:331:40: warning: unused parameter ‘auxil’ [-Wunused-parameter]
  331 | static char *pcc_strndup_e(pcc_auxil_t auxil, const char *str, size_t len) {
      |                            ~~~~~~~~~~~~^~~~~
parser.c: In function ‘pcc_char_array__init’:
parser.c:339:46: warning: unused parameter ‘auxil’ [-Wunused-parameter]
  339 | static void pcc_char_array__init(pcc_auxil_t auxil, pcc_char_array_t *array) {
      |                                  ~~~~~~~~~~~~^~~~~
parser.c: In function ‘pcc_char_array__add’:
parser.c:345:45: warning: unused parameter ‘auxil’ [-Wunused-parameter]
  345 | static void pcc_char_array__add(pcc_auxil_t auxil, pcc_char_array_t *array, char ch) {
      |                                 ~~~~~~~~~~~~^~~~~
parser.c: In function ‘pcc_char_array__term’:
parser.c:358:46: warning: unused parameter ‘auxil’ [-Wunused-parameter]
  358 | static void pcc_char_array__term(pcc_auxil_t auxil, pcc_char_array_t *array) {
      |                                  ~~~~~~~~~~~~^~~~~
parser.c: In function ‘pcc_value_table__init’:
parser.c:362:47: warning: unused parameter ‘auxil’ [-Wunused-parameter]
  362 | static void pcc_value_table__init(pcc_auxil_t auxil, pcc_value_table_t *table) {
      |                                   ~~~~~~~~~~~~^~~~~
parser.c: In function ‘pcc_value_table__resize’:
parser.c:369:49: warning: unused parameter ‘auxil’ [-Wunused-parameter]
  369 | static void pcc_value_table__resize(pcc_auxil_t auxil, pcc_value_table_t *table, size_t len) {
      |                                     ~~~~~~~~~~~~^~~~~
parser.c: In function ‘pcc_value_table__clear’:
parser.c:382:48: warning: unused parameter ‘auxil’ [-Wunused-parameter]
  382 | static void pcc_value_table__clear(pcc_auxil_t auxil, pcc_value_table_t *table) {
      |                                    ~~~~~~~~~~~~^~~~~
parser.c: In function ‘pcc_value_table__term’:
parser.c:386:47: warning: unused parameter ‘auxil’ [-Wunused-parameter]
  386 | static void pcc_value_table__term(pcc_auxil_t auxil, pcc_value_table_t *table) {
      |                                   ~~~~~~~~~~~~^~~~~
parser.c: In function ‘pcc_value_refer_table__init’:
parser.c:390:53: warning: unused parameter ‘auxil’ [-Wunused-parameter]
  390 | static void pcc_value_refer_table__init(pcc_auxil_t auxil, pcc_value_refer_table_t *table) {
      |                                         ~~~~~~~~~~~~^~~~~
parser.c: In function ‘pcc_value_refer_table__resize’:
parser.c:396:55: warning: unused parameter ‘auxil’ [-Wunused-parameter]
  396 | static void pcc_value_refer_table__resize(pcc_auxil_t auxil, pcc_value_refer_table_t *table, size_t len) {
      |                                           ~~~~~~~~~~~~^~~~~
parser.c: In function ‘pcc_value_refer_table__term’:
parser.c:410:53: warning: unused parameter ‘auxil’ [-Wunused-parameter]
  410 | static void pcc_value_refer_table__term(pcc_auxil_t auxil, pcc_value_refer_table_t *table) {
      |                                         ~~~~~~~~~~~~^~~~~
parser.c: In function ‘pcc_capture_table__init’:
parser.c:414:49: warning: unused parameter ‘auxil’ [-Wunused-parameter]
  414 | static void pcc_capture_table__init(pcc_auxil_t auxil, pcc_capture_table_t *table) {
      |                                     ~~~~~~~~~~~~^~~~~
parser.c: In function ‘pcc_capture_table__resize’:
parser.c:421:51: warning: unused parameter ‘auxil’ [-Wunused-parameter]
  421 | static void pcc_capture_table__resize(pcc_auxil_t auxil, pcc_capture_table_t *table, size_t len) {
      |                                       ~~~~~~~~~~~~^~~~~
parser.c: In function ‘pcc_capture_table__term’:
parser.c:440:49: warning: unused parameter ‘auxil’ [-Wunused-parameter]
  440 | static void pcc_capture_table__term(pcc_auxil_t auxil, pcc_capture_table_t *table) {
      |                                     ~~~~~~~~~~~~^~~~~
parser.c: In function ‘pcc_capture_const_table__init’:
parser.c:448:55: warning: unused parameter ‘auxil’ [-Wunused-parameter]
  448 | static void pcc_capture_const_table__init(pcc_auxil_t auxil, pcc_capture_const_table_t *table) {
      |                                           ~~~~~~~~~~~~^~~~~
parser.c: In function ‘pcc_capture_const_table__resize’:
parser.c:454:57: warning: unused parameter ‘auxil’ [-Wunused-parameter]
  454 | static void pcc_capture_const_table__resize(pcc_auxil_t auxil, pcc_capture_const_table_t *table, size_t len) {
      |                                             ~~~~~~~~~~~~^~~~~
parser.c: In function ‘pcc_capture_const_table__term’:
parser.c:468:55: warning: unused parameter ‘auxil’ [-Wunused-parameter]
  468 | static void pcc_capture_const_table__term(pcc_auxil_t auxil, pcc_capture_const_table_t *table) {
      |                                           ~~~~~~~~~~~~^~~~~
parser.c: In function ‘pcc_thunk__create_node’:
parser.c:487:56: warning: unused parameter ‘auxil’ [-Wunused-parameter]
  487 | static pcc_thunk_t *pcc_thunk__create_node(pcc_auxil_t auxil, const pcc_thunk_array_t *thunks, pcc_value_t *value) {
      |                                            ~~~~~~~~~~~~^~~~~
parser.c: In function ‘pcc_thunk_array__init’:
parser.c:511:47: warning: unused parameter ‘auxil’ [-Wunused-parameter]
  511 | static void pcc_thunk_array__init(pcc_auxil_t auxil, pcc_thunk_array_t *array) {
      |                                   ~~~~~~~~~~~~^~~~~
parser.c: In function ‘pcc_thunk_array__add’:
parser.c:517:46: warning: unused parameter ‘auxil’ [-Wunused-parameter]
  517 | static void pcc_thunk_array__add(pcc_auxil_t auxil, pcc_thunk_array_t *array, pcc_thunk_t *thunk) {
      |                                  ~~~~~~~~~~~~^~~~~
parser.c: In function ‘pcc_memory_recycler__init’:
parser.c:545:51: warning: unused parameter ‘auxil’ [-Wunused-parameter]
  545 | static void pcc_memory_recycler__init(pcc_auxil_t auxil, pcc_memory_recycler_t *recycler, size_t element_size) {
      |                                       ~~~~~~~~~~~~^~~~~
parser.c: In function ‘pcc_memory_recycler__supply’:
parser.c:551:54: warning: unused parameter ‘auxil’ [-Wunused-parameter]
  551 | static void *pcc_memory_recycler__supply(pcc_auxil_t auxil, pcc_memory_recycler_t *recycler) {
      |                                          ~~~~~~~~~~~~^~~~~
parser.c: In function ‘pcc_memory_recycler__recycle’:
parser.c:577:54: warning: unused parameter ‘auxil’ [-Wunused-parameter]
  577 | static void pcc_memory_recycler__recycle(pcc_auxil_t auxil, pcc_memory_recycler_t *recycler, void *ptr) {
      |                                          ~~~~~~~~~~~~^~~~~
parser.c: In function ‘pcc_memory_recycler__term’:
parser.c:583:51: warning: unused parameter ‘auxil’ [-Wunused-parameter]
  583 | static void pcc_memory_recycler__term(pcc_auxil_t auxil, pcc_memory_recycler_t *recycler) {
      |                                       ~~~~~~~~~~~~^~~~~
parser.c: In function ‘pcc_rule_set__init’:
parser.c:609:44: warning: unused parameter ‘auxil’ [-Wunused-parameter]
  609 | static void pcc_rule_set__init(pcc_auxil_t auxil, pcc_rule_set_t *set) {
      |                                ~~~~~~~~~~~~^~~~~
parser.c: In function ‘pcc_rule_set__index’:
parser.c:615:47: warning: unused parameter ‘auxil’ [-Wunused-parameter]
  615 | static size_t pcc_rule_set__index(pcc_auxil_t auxil, const pcc_rule_set_t *set, pcc_rule_t rule) {
      |                                   ~~~~~~~~~~~~^~~~~
parser.c: In function ‘pcc_rule_set__clear’:
parser.c:646:45: warning: unused parameter ‘auxil’ [-Wunused-parameter]
  646 | static void pcc_rule_set__clear(pcc_auxil_t auxil, pcc_rule_set_t *set) {
      |                                 ~~~~~~~~~~~~^~~~~
parser.c: In function ‘pcc_rule_set__term’:
parser.c:658:44: warning: unused parameter ‘auxil’ [-Wunused-parameter]
  658 | static void pcc_rule_set__term(pcc_auxil_t auxil, pcc_rule_set_t *set) {
      |                                ~~~~~~~~~~~~^~~~~
parser.c: In function ‘pcc_lr_memo_map__init’:
parser.c:736:47: warning: unused parameter ‘auxil’ [-Wunused-parameter]
  736 | static void pcc_lr_memo_map__init(pcc_auxil_t auxil, pcc_lr_memo_map_t *map) {
      |                                   ~~~~~~~~~~~~^~~~~
parser.c: In function ‘pcc_lr_memo_map__index’:
parser.c:742:53: warning: unused parameter ‘ctx’ [-Wunused-parameter]
  742 | static size_t pcc_lr_memo_map__index(pcc_context_t *ctx, pcc_lr_memo_map_t *map, pcc_rule_t rule) {
      |                                      ~~~~~~~~~~~~~~~^~~
parser.c: In function ‘pcc_lr_table__init’:
parser.c:802:44: warning: unused parameter ‘auxil’ [-Wunused-parameter]
  802 | static void pcc_lr_table__init(pcc_auxil_t auxil, pcc_lr_table_t *table) {
      |                                ~~~~~~~~~~~~^~~~~
parser.c: In function ‘pcc_lr_table__get_head’:
parser.c:854:61: warning: unused parameter ‘ctx’ [-Wunused-parameter]
  854 | static pcc_lr_head_t *pcc_lr_table__get_head(pcc_context_t *ctx, pcc_lr_table_t *table, size_t index) {
      |                                              ~~~~~~~~~~~~~~~^~~
parser.c: In function ‘pcc_lr_entry__create’:
parser.c:885:57: warning: unused parameter ‘auxil’ [-Wunused-parameter]
  885 | static pcc_lr_entry_t *pcc_lr_entry__create(pcc_auxil_t auxil, pcc_rule_t rule) {
      |                                             ~~~~~~~~~~~~^~~~~
parser.c: In function ‘pcc_lr_entry__destroy’:
parser.c:893:47: warning: unused parameter ‘auxil’ [-Wunused-parameter]
  893 | static void pcc_lr_entry__destroy(pcc_auxil_t auxil, pcc_lr_entry_t *lr) {
      |                                   ~~~~~~~~~~~~^~~~~
parser.c: In function ‘pcc_lr_stack__init’:
parser.c:897:44: warning: unused parameter ‘auxil’ [-Wunused-parameter]
  897 | static void pcc_lr_stack__init(pcc_auxil_t auxil, pcc_lr_stack_t *stack) {
      |                                ~~~~~~~~~~~~^~~~~
parser.c: In function ‘pcc_lr_stack__push’:
parser.c:903:44: warning: unused parameter ‘auxil’ [-Wunused-parameter]
  903 | static void pcc_lr_stack__push(pcc_auxil_t auxil, pcc_lr_stack_t *stack, pcc_lr_entry_t *lr) {
      |                                ~~~~~~~~~~~~^~~~~
parser.c: In function ‘pcc_lr_stack__pop’:
parser.c:916:54: warning: unused parameter ‘auxil’ [-Wunused-parameter]
  916 | static pcc_lr_entry_t *pcc_lr_stack__pop(pcc_auxil_t auxil, pcc_lr_stack_t *stack) {
      |                                          ~~~~~~~~~~~~^~~~~
parser.c: In function ‘pcc_lr_stack__term’:
parser.c:920:44: warning: unused parameter ‘auxil’ [-Wunused-parameter]
  920 | static void pcc_lr_stack__term(pcc_auxil_t auxil, pcc_lr_stack_t *stack) {
      |                                ~~~~~~~~~~~~^~~~~
parser.c: In function ‘pcc_action_Xvalue_0’:
parser.c:1149:95: warning: unused parameter ‘__pcc_out’ [-Wunused-parameter]
 1149 | static void pcc_action_Xvalue_0(pcc_context_t *__pcc_ctx, pcc_thunk_t *__pcc_in, pcc_value_t *__pcc_out) {
      |                                                                                  ~~~~~~~~~~~~~^~~~~~~~~
parser.c: In function ‘pcc_action_Kheader_0’:
parser.c:1169:96: warning: unused parameter ‘__pcc_out’ [-Wunused-parameter]
 1169 | static void pcc_action_Kheader_0(pcc_context_t *__pcc_ctx, pcc_thunk_t *__pcc_in, pcc_value_t *__pcc_out) {
      |                                                                                   ~~~~~~~~~~~~~^~~~~~~~~
parser.c: In function ‘pcc_action_Iheader_0’:
parser.c:1189:96: warning: unused parameter ‘__pcc_out’ [-Wunused-parameter]
 1189 | static void pcc_action_Iheader_0(pcc_context_t *__pcc_ctx, pcc_thunk_t *__pcc_in, pcc_value_t *__pcc_out) {
      |                                                                                   ~~~~~~~~~~~~~^~~~~~~~~
parser.c: In function ‘pcc_action_Iheader_1’:
parser.c:1209:96: warning: unused parameter ‘__pcc_out’ [-Wunused-parameter]
 1209 | static void pcc_action_Iheader_1(pcc_context_t *__pcc_ctx, pcc_thunk_t *__pcc_in, pcc_value_t *__pcc_out) {
      |                                                                                   ~~~~~~~~~~~~~^~~~~~~~~
parser.c: In function ‘pcc_action_Oheader_0’:
parser.c:1249:96: warning: unused parameter ‘__pcc_out’ [-Wunused-parameter]
 1249 | static void pcc_action_Oheader_0(pcc_context_t *__pcc_ctx, pcc_thunk_t *__pcc_in, pcc_value_t *__pcc_out) {
      |                                                                                   ~~~~~~~~~~~~~^~~~~~~~~
parser.c: In function ‘pcc_action_KeySig_0’:
parser.c:1271:95: warning: unused parameter ‘__pcc_out’ [-Wunused-parameter]
 1271 | static void pcc_action_KeySig_0(pcc_context_t *__pcc_ctx, pcc_thunk_t *__pcc_in, pcc_value_t *__pcc_out) {
      |                                                                                  ~~~~~~~~~~~~~^~~~~~~~~
parser.c: In function ‘pcc_action_Unit_0’:
parser.c:1291:93: warning: unused parameter ‘__pcc_out’ [-Wunused-parameter]
 1291 | static void pcc_action_Unit_0(pcc_context_t *__pcc_ctx, pcc_thunk_t *__pcc_in, pcc_value_t *__pcc_out) {
      |                                                                                ~~~~~~~~~~~~~^~~~~~~~~
parser.c: In function ‘pcc_action_TimeSig_0’:
parser.c:1311:96: warning: unused parameter ‘__pcc_out’ [-Wunused-parameter]
 1311 | static void pcc_action_TimeSig_0(pcc_context_t *__pcc_ctx, pcc_thunk_t *__pcc_in, pcc_value_t *__pcc_out) {
      |                                                                                   ~~~~~~~~~~~~~^~~~~~~~~
parser.c: In function ‘pcc_action_Tempo_0’:
parser.c:1331:94: warning: unused parameter ‘__pcc_out’ [-Wunused-parameter]
 1331 | static void pcc_action_Tempo_0(pcc_context_t *__pcc_ctx, pcc_thunk_t *__pcc_in, pcc_value_t *__pcc_out) {
      |                                                                                 ~~~~~~~~~~~~~^~~~~~~~~
parser.c: In function ‘pcc_action_Vvalue_0’:
parser.c:1351:95: warning: unused parameter ‘__pcc_out’ [-Wunused-parameter]
 1351 | static void pcc_action_Vvalue_0(pcc_context_t *__pcc_ctx, pcc_thunk_t *__pcc_in, pcc_value_t *__pcc_out) {
      |                                                                                  ~~~~~~~~~~~~~^~~~~~~~~
parser.c: In function ‘pcc_action_ChordPunct_0’:
parser.c:1371:99: warning: unused parameter ‘__pcc_out’ [-Wunused-parameter]
 1371 | static void pcc_action_ChordPunct_0(pcc_context_t *__pcc_ctx, pcc_thunk_t *__pcc_in, pcc_value_t *__pcc_out) {
      |                                                                                      ~~~~~~~~~~~~~^~~~~~~~~
parser.c: In function ‘pcc_action_NotePunct_0’:
parser.c:1391:98: warning: unused parameter ‘__pcc_out’ [-Wunused-parameter]
 1391 | static void pcc_action_NotePunct_0(pcc_context_t *__pcc_ctx, pcc_thunk_t *__pcc_in, pcc_value_t *__pcc_out) {
      |                                                                                     ~~~~~~~~~~~~~^~~~~~~~~
parser.c: In function ‘pcc_action_MidiInstruction_0’:
parser.c:1411:104: warning: unused parameter ‘__pcc_out’ [-Wunused-parameter]
 1411 | static void pcc_action_MidiInstruction_0(pcc_context_t *__pcc_ctx, pcc_thunk_t *__pcc_in, pcc_value_t *__pcc_out) {
      |                                                                                           ~~~~~~~~~~~~~^~~~~~~~~
parser.c: In function ‘pcc_action_Lyrics_0’:
parser.c:1431:95: warning: unused parameter ‘__pcc_out’ [-Wunused-parameter]
 1431 | static void pcc_action_Lyrics_0(pcc_context_t *__pcc_ctx, pcc_thunk_t *__pcc_in, pcc_value_t *__pcc_out) {
      |                                                                                  ~~~~~~~~~~~~~^~~~~~~~~
parser.c: In function ‘pcc_action_Tie_0’:
parser.c:1451:92: warning: unused parameter ‘__pcc_out’ [-Wunused-parameter]
 1451 | static void pcc_action_Tie_0(pcc_context_t *__pcc_ctx, pcc_thunk_t *__pcc_in, pcc_value_t *__pcc_out) {
      |                                                                               ~~~~~~~~~~~~~^~~~~~~~~
parser.c: In function ‘pcc_action_Grace_0’:
parser.c:1471:94: warning: unused parameter ‘__pcc_out’ [-Wunused-parameter]
 1471 | static void pcc_action_Grace_0(pcc_context_t *__pcc_ctx, pcc_thunk_t *__pcc_in, pcc_value_t *__pcc_out) {
      |                                                                                 ~~~~~~~~~~~~~^~~~~~~~~
parser.c: In function ‘pcc_action_Grace_1’:
parser.c:1491:94: warning: unused parameter ‘__pcc_out’ [-Wunused-parameter]
 1491 | static void pcc_action_Grace_1(pcc_context_t *__pcc_ctx, pcc_thunk_t *__pcc_in, pcc_value_t *__pcc_out) {
      |                                                                                 ~~~~~~~~~~~~~^~~~~~~~~
parser.c: In function ‘pcc_action_Chord_0’:
parser.c:1517:94: warning: unused parameter ‘__pcc_out’ [-Wunused-parameter]
 1517 | static void pcc_action_Chord_0(pcc_context_t *__pcc_ctx, pcc_thunk_t *__pcc_in, pcc_value_t *__pcc_out) {
      |                                                                                 ~~~~~~~~~~~~~^~~~~~~~~
parser.c: In function ‘pcc_action_Chord_1’:
parser.c:1537:94: warning: unused parameter ‘__pcc_out’ [-Wunused-parameter]
 1537 | static void pcc_action_Chord_1(pcc_context_t *__pcc_ctx, pcc_thunk_t *__pcc_in, pcc_value_t *__pcc_out) {
      |                                                                                 ~~~~~~~~~~~~~^~~~~~~~~
parser.c: In function ‘pcc_action___0’:
parser.c:1563:90: warning: unused parameter ‘__pcc_out’ [-Wunused-parameter]
 1563 | static void pcc_action___0(pcc_context_t *__pcc_ctx, pcc_thunk_t *__pcc_in, pcc_value_t *__pcc_out) {
      |                                                                             ~~~~~~~~~~~~~^~~~~~~~~
parser.c: In function ‘pcc_action_Decoration_0’:
parser.c:1583:99: warning: unused parameter ‘__pcc_out’ [-Wunused-parameter]
 1583 | static void pcc_action_Decoration_0(pcc_context_t *__pcc_ctx, pcc_thunk_t *__pcc_in, pcc_value_t *__pcc_out) {
      |                                                                                      ~~~~~~~~~~~~~^~~~~~~~~
parser.c: In function ‘pcc_action_ExDecoration_0’:
parser.c:1603:101: warning: unused parameter ‘__pcc_out’ [-Wunused-parameter]
 1603 | static void pcc_action_ExDecoration_0(pcc_context_t *__pcc_ctx, pcc_thunk_t *__pcc_in, pcc_value_t *__pcc_out) {
      |                                                                                        ~~~~~~~~~~~~~^~~~~~~~~
parser.c: In function ‘pcc_action_Nuplet_0’:
parser.c:1623:95: warning: unused parameter ‘__pcc_out’ [-Wunused-parameter]
 1623 | static void pcc_action_Nuplet_0(pcc_context_t *__pcc_ctx, pcc_thunk_t *__pcc_in, pcc_value_t *__pcc_out) {
      |                                                                                  ~~~~~~~~~~~~~^~~~~~~~~
parser.c: In function ‘pcc_action_Nuplet_1’:
parser.c:1639:95: warning: unused parameter ‘__pcc_out’ [-Wunused-parameter]
 1639 | static void pcc_action_Nuplet_1(pcc_context_t *__pcc_ctx, pcc_thunk_t *__pcc_in, pcc_value_t *__pcc_out) {
      |                                                                                  ~~~~~~~~~~~~~^~~~~~~~~
parser.c: In function ‘pcc_action_Nuplet_2’:
parser.c:1659:95: warning: unused parameter ‘__pcc_out’ [-Wunused-parameter]
 1659 | static void pcc_action_Nuplet_2(pcc_context_t *__pcc_ctx, pcc_thunk_t *__pcc_in, pcc_value_t *__pcc_out) {
      |                                                                                  ~~~~~~~~~~~~~^~~~~~~~~
parser.c: In function ‘pcc_action_Nuplet_3’:
parser.c:1677:95: warning: unused parameter ‘__pcc_out’ [-Wunused-parameter]
 1677 | static void pcc_action_Nuplet_3(pcc_context_t *__pcc_ctx, pcc_thunk_t *__pcc_in, pcc_value_t *__pcc_out) {
      |                                                                                  ~~~~~~~~~~~~~^~~~~~~~~
parser.c: In function ‘pcc_action_Gchord_0’:
parser.c:1713:95: warning: unused parameter ‘__pcc_out’ [-Wunused-parameter]
 1713 | static void pcc_action_Gchord_0(pcc_context_t *__pcc_ctx, pcc_thunk_t *__pcc_in, pcc_value_t *__pcc_out) {
      |                                                                                  ~~~~~~~~~~~~~^~~~~~~~~
parser.c: In function ‘pcc_action_SlurStart_0’:
parser.c:1733:98: warning: unused parameter ‘__pcc_out’ [-Wunused-parameter]
 1733 | static void pcc_action_SlurStart_0(pcc_context_t *__pcc_ctx, pcc_thunk_t *__pcc_in, pcc_value_t *__pcc_out) {
      |                                                                                     ~~~~~~~~~~~~~^~~~~~~~~
parser.c: In function ‘pcc_action_SlurEnd_0’:
parser.c:1753:96: warning: unused parameter ‘__pcc_out’ [-Wunused-parameter]
 1753 | static void pcc_action_SlurEnd_0(pcc_context_t *__pcc_ctx, pcc_thunk_t *__pcc_in, pcc_value_t *__pcc_out) {
      |                                                                                   ~~~~~~~~~~~~~^~~~~~~~~
parser.c: In function ‘pcc_action_SimpleAlter_0’:
parser.c:1773:100: warning: unused parameter ‘__pcc_out’ [-Wunused-parameter]
 1773 | static void pcc_action_SimpleAlter_0(pcc_context_t *__pcc_ctx, pcc_thunk_t *__pcc_in, pcc_value_t *__pcc_out) {
      |                                                                                       ~~~~~~~~~~~~~^~~~~~~~~
parser.c: In function ‘pcc_action_Alternative_0’:
parser.c:1793:100: warning: unused parameter ‘__pcc_out’ [-Wunused-parameter]
 1793 | static void pcc_action_Alternative_0(pcc_context_t *__pcc_ctx, pcc_thunk_t *__pcc_in, pcc_value_t *__pcc_out) {
      |                                                                                       ~~~~~~~~~~~~~^~~~~~~~~
parser.c: In function ‘pcc_action_Bar_0’:
parser.c:1813:92: warning: unused parameter ‘__pcc_out’ [-Wunused-parameter]
 1813 | static void pcc_action_Bar_0(pcc_context_t *__pcc_ctx, pcc_thunk_t *__pcc_in, pcc_value_t *__pcc_out) {
      |                                                                               ~~~~~~~~~~~~~^~~~~~~~~
parser.c: In function ‘pcc_action_ChordDuration_0’:
parser.c:1833:102: warning: unused parameter ‘__pcc_out’ [-Wunused-parameter]
 1833 | static void pcc_action_ChordDuration_0(pcc_context_t *__pcc_ctx, pcc_thunk_t *__pcc_in, pcc_value_t *__pcc_out) {
      |                                                                                         ~~~~~~~~~~~~~^~~~~~~~~
parser.c: In function ‘pcc_action_ChordDuration_1’:
parser.c:1853:102: warning: unused parameter ‘__pcc_out’ [-Wunused-parameter]
 1853 | static void pcc_action_ChordDuration_1(pcc_context_t *__pcc_ctx, pcc_thunk_t *__pcc_in, pcc_value_t *__pcc_out) {
      |                                                                                         ~~~~~~~~~~~~~^~~~~~~~~
parser.c: In function ‘pcc_action_ChordDuration_2’:
parser.c:1879:102: warning: unused parameter ‘__pcc_out’ [-Wunused-parameter]
 1879 | static void pcc_action_ChordDuration_2(pcc_context_t *__pcc_ctx, pcc_thunk_t *__pcc_in, pcc_value_t *__pcc_out) {
      |                                                                                         ~~~~~~~~~~~~~^~~~~~~~~
parser.c: In function ‘pcc_action_ChordDuration_3’:
parser.c:1899:102: warning: unused parameter ‘__pcc_out’ [-Wunused-parameter]
 1899 | static void pcc_action_ChordDuration_3(pcc_context_t *__pcc_ctx, pcc_thunk_t *__pcc_in, pcc_value_t *__pcc_out) {
      |                                                                                         ~~~~~~~~~~~~~^~~~~~~~~
parser.c: In function ‘pcc_action_NoteDuration_0’:
parser.c:1919:101: warning: unused parameter ‘__pcc_out’ [-Wunused-parameter]
 1919 | static void pcc_action_NoteDuration_0(pcc_context_t *__pcc_ctx, pcc_thunk_t *__pcc_in, pcc_value_t *__pcc_out) {
      |                                                                                        ~~~~~~~~~~~~~^~~~~~~~~
parser.c: In function ‘pcc_action_NoteDuration_1’:
parser.c:1939:101: warning: unused parameter ‘__pcc_out’ [-Wunused-parameter]
 1939 | static void pcc_action_NoteDuration_1(pcc_context_t *__pcc_ctx, pcc_thunk_t *__pcc_in, pcc_value_t *__pcc_out) {
      |                                                                                        ~~~~~~~~~~~~~^~~~~~~~~
parser.c: In function ‘pcc_action_NoteDuration_2’:
parser.c:1965:101: warning: unused parameter ‘__pcc_out’ [-Wunused-parameter]
 1965 | static void pcc_action_NoteDuration_2(pcc_context_t *__pcc_ctx, pcc_thunk_t *__pcc_in, pcc_value_t *__pcc_out) {
      |                                                                                        ~~~~~~~~~~~~~^~~~~~~~~
parser.c: In function ‘pcc_action_NoteDuration_3’:
parser.c:1985:101: warning: unused parameter ‘__pcc_out’ [-Wunused-parameter]
 1985 | static void pcc_action_NoteDuration_3(pcc_context_t *__pcc_ctx, pcc_thunk_t *__pcc_in, pcc_value_t *__pcc_out) {
      |                                                                                        ~~~~~~~~~~~~~^~~~~~~~~
parser.c: In function ‘pcc_action_Note_0’:
parser.c:2005:93: warning: unused parameter ‘__pcc_out’ [-Wunused-parameter]
 2005 | static void pcc_action_Note_0(pcc_context_t *__pcc_ctx, pcc_thunk_t *__pcc_in, pcc_value_t *__pcc_out) {
      |                                                                                ~~~~~~~~~~~~~^~~~~~~~~
parser.c: In function ‘pcc_action_LineBreak_0’:
parser.c:2025:98: warning: unused parameter ‘__pcc_out’ [-Wunused-parameter]
 2025 | static void pcc_action_LineBreak_0(pcc_context_t *__pcc_ctx, pcc_thunk_t *__pcc_in, pcc_value_t *__pcc_out) {
      |                                                                                     ~~~~~~~~~~~~~^~~~~~~~~
parser.c: In function ‘pcc_action_LineBreak_1’:
parser.c:2045:98: warning: unused parameter ‘__pcc_out’ [-Wunused-parameter]
 2045 | static void pcc_action_LineBreak_1(pcc_context_t *__pcc_ctx, pcc_thunk_t *__pcc_in, pcc_value_t *__pcc_out) {
      |

**Comment by be1** [comment]
indeed. harmless :)
parser.c is generated by `packcc parser.peg` and i cannot control its code.
