### ISSUE TITLE
problem building on Linux

### ISSUE THREAD

**Issue by topchyan** [be1/redrose#3]
I ran into some issues while trying to build it

```
parser.c: In function ‘pcc_action_LineBreak_0’:
parser.c:1986:98: warning: unused parameter ‘__pcc_out’ [-Wunused-parameter]
 1986 | ction_LineBreak_0(pcc_context_t *__pcc_ctx, pcc_thunk_t *__pcc_in, pcc_value_t *__pcc_out) {
      |                                                                    ~~~~~~~~~~~~~^~~~~~~~~

rm -f libabc.a
ar cqs libabc.a abc.o parser.o
make[1]: Leaving directory '/media/avetik/SdCard/Projects/GitHub/redrose/abc'
cd app/ && ( test -e Makefile || /usr/lib/qt5/bin/qmake -o Makefile /media/avetik/SdCard/Projects/GitHub/redrose/app/app.pro -config release ) && make -f Makefile 
make[1]: Entering directory '/media/avetik/SdCard/Projects/GitHub/redrose/app'
/usr/lib/qt5/bin/lrelease redrose_en.ts -qm locale/redrose_en.qm
make[1]: /usr/lib/qt5/bin/lrelease: No such file or directory
make[1]: *** [Makefile:527: locale/redrose_en.qm] Error 127
make[1]: Leaving directory '/media/avetik/SdCard/Projects/GitHub/redrose/app'
make: *** [Makefile:73: sub-app-make_first] Error 2
```

**Comment by be1** [comment]
```
...
make[1]: /usr/lib/qt5/bin/lrelease: No such file or directory
make[1]: *** [Makefile:527: locale/redrose_en.qm] Error 127
```
You must install the package that provides `lrelease`

**Comment by be1** [comment]
In Debian and Ubuntu, the package is `qttools5-dev-tools`:
```
$ dpkg -S /usr/lib/qt5/bin/lrelease
qttools5-dev-tools: /usr/lib/qt5/bin/lrelease
```
If you have another Linux distribution, please post the name of the distribution and the name of the package providing `lrelease` for that distribution, so that other people having the same distro as you can refer to your post.

**Comment by topchyan** [comment]
Okay, installing `qttools5-dev-tools` indeed helped to run the make okay. Only one warning noticed:

```
abcsynth.cpp:10:12: warning: ‘int handle_midi_tick(void*, int)’ defined but not used [-Wunused-function]
   10 | static int handle_midi_tick(void *data, int tick) {
      | 
```

Is this something to check?

**Comment by topchyan** [comment]
Rendering the score is working, but not the playback

![image](https://github.com/be1/redrose/assets/16518288/48bc8c32-ef90-4fc2-98c9-aa5f4d6645ef)

**Comment by be1** [comment]
> Okay, installing `qttools5-dev-tools` indeed helped to run the make okay. Only one warning noticed:
> 
> ```
> abcsynth.cpp:10:12: warning: ‘int handle_midi_tick(void*, int)’ defined but not used [-Wunused-function]
>    10 | static int handle_midi_tick(void *data, int tick) {
>       | 
> ```
> 
> Is this something to check?

Nothing important. This unused code is for future usage...

About Playback, please go to Preferences->Player settings, and choose abc2midi as MIDI generator, instead of "internal".
The internal parser is somewhat experimental. You may prefer abc2midi.
