### ISSUE TITLE
Font selection

### ISSUE THREAD

**Issue by topchyan** [be1/redrose#4]
Would it be possible to add font selection (name and size) for each text style or at least a single font choice other than the default?

**Comment by be1** [comment]
Nice idea ! I will look how I can do it.

**Comment by be1** [comment]
I propose to split as this:
- add single font name and size selection (should be available in version 0.5.12)
- add italic / bold checkboxes as preferences for each text styles (should be available in a future version)

**Comment by be1** [comment]
first phase of font selection in settings is now implemented in fed5d2fcf7ea3bee86f974328cf74c6aefe4aba4

**Comment by topchyan** [comment]
![image](https://github.com/be1/redrose/assets/16518288/95726321-3cbf-4e95-8cad-ad3967f63945)

Looks really good! The only thing is that pressing OK button doesn't have an effect on the currently loaded file: upon restarting the program these changes take effect. Is it possible to reload that particular window with changes?

**Comment by be1** [comment]
Currently, this only have effect on newly opened tabs. No need to restart the application though. Just close and reopen the file for now... Maybe a later version will implement on-the-fly settings changes.

**Comment by topchyan** [comment]
Thank you! I'll try to add other issues I stumble upon.
