### ISSUE TITLE
Markup X: does not get recognized if immediately follows the % from a previous tune

### ISSUE THREAD

**Issue by topchyan** [be1/redrose#5]
![image](https://github.com/be1/redrose/assets/16518288/c53ed0ac-e310-4a17-8cfb-c96b8433efdf)

**Comment by be1** [comment]
according to https://abcnotation.com/wiki/abc:standard:v2.2#abc_tune each tune must be preceeded by a newline somewhere. Do you have any newline between end of tune 33 and X:34 field ?

**Comment by be1** [comment]
Won't fix, since standard says a blank line must separate tunes.

**Comment by be1** [comment]
Won't fix, as standard says a blank line must separate tunes from each other.
