### ISSUE TITLE
Markup X: disconnect between score rendering / playback / selection

### ISSUE THREAD

**Issue by topchyan** [be1/redrose#6]
In this example I am looking at a song **X:34** and try to press Play or View Score buttons expecting to see and edit that song, but instead the program is attempting to render a song number **X:4** and does not go any further. I tried to change it by both scrolling and changing the little box with the number, but it doesn't work.

![image](https://github.com/be1/redrose/assets/16518288/8da9a53c-7049-4310-bc4b-9e356853d741)

**Comment by be1** [comment]
Thank you for your report. I identified the bug in the source code, line 407 of EditVboxLayout.cpp
